services:
  api:
    image: ghcr.io/bagasadityap/api-pinjam100:development
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: prod

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pinjam100
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}

      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/firebase-credentials.json

      FLOWKIRIM_BASE_URL: ${FLOWKIRIM_BASE_URL}
      FLOWKIRIM_API_TOKEN: ${FLOWKIRIM_API_TOKEN}
      FLOWKIRIM_DEVICE_ID: ${FLOWKIRIM_DEVICE_ID}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

    volumes:
      - ./secrets/firebase-credentials.json:/app/secrets/firebase-credentials.json:ro

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    restart: unless-stopped

    environment:
      POSTGRES_DB: pinjam100
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d pinjam100"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: >
      sh -c 'if [ -n "$REDIS_PASSWORD" ]; then
        exec redis-server --requirepass "$REDIS_PASSWORD";
      else
        exec redis-server;
      fi'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: >
        sh -c 'if [ -n "$REDIS_PASSWORD" ]; then
          redis-cli -a "$REDIS_PASSWORD" ping | grep PONG;
        else
          redis-cli ping | grep PONG;
        fi'
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: