spring.config.import=optional:file:.env[.properties]

spring.application.name=${APPLICATION_NAME:bagas.pinjam100}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
app.security.jwt-secret=${JWT_SECRET}
app.security.jwt-ttl-minutes=15
app.security.refresh-token-ttl-days=30
app.security.password=${DEMO_PASSWORD}
app.security.rate-limit-per-minute=10
app.storage.image-dir=uploads/images
app.storage.file-dir=uploads/files

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

app.security.crypto-key=${CRYPTO_KEY}

spring.web.error.include-stacktrace=never
spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
spring.web.error.include-exception=false

app.security.cors-allowed-origins=https://pinjam100.bagasaditya.com
app.redis.key-prefix=${REDIS_KEY_PREFIX:bagas:${spring.profile.active:dev}}
app.redis.host=${REDIS_HOST:redis}
app.redis.port=${REDIS_PORT:6379}
app.redis.timeout=${REDIS_TIMEOUT:10000ms}
app.redis.username=${REDIS_USERNAME:}
app.redis.password=${REDIS_PASSWORD:}
app.redis.lettuce-pool-max-active=100
app.redis.lettuce-pool-max-wait=1ms
app.redis.lettuce-pool-max-idle=50
app.redis.lettuce-pool-min-idle=10

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

server.servlet.context-path=/api

flowkirim.base-url=https://scan.flowkirim.com
flowkirim.api-token=${FLOWKIRIM_API_TOKEN}
flowkirim.device-id=${FLOWKIRIM_DEVICE_ID}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jackson.time-zone=Asia/Jakarta